### PR TITLE
Fix typescript definitions

### LINKED ISSUE #133: Typescript definition missing important properties or has properties that should be optional.
Causes huge walls of (invalid) errors in our codebase after upgrading to 2.4.0.  I've taken to rm'ing `index.d.ts` for now :)

The issues are:

* `Router` has no `history` prop.
* `RouterArgs.matches` should be optional.
* `RouterArgs.url` should be optional.
* `RouterArgs.path` should be present.

I think that's all, but don't have time atm to try to fix or dig deeper so there may be others.

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes errors present in strict mode

Adds getCurrentUrl and route override definitions

Adds a RoutableProps interface consumers can extend to implement a routable component

Fixes the types of RouterProps, Route, Link (closes #133)

Re-enables the typings file in package.json

### CODE REVIEW

File: src/index.d.ts [hunk 1]
```diff
@@ -1,4 +1,9 @@
+import * as preact from 'preact';
+
 export function route(url: string, replace?: boolean): boolean;
+export function route(options: { url: string; replace?: boolean }): boolean;
```
Comment (developit) [inline src/index.d.ts]: I think it allows both formats?  Definitely supports `route(url, replace)`.

**Comment by UnwrittenFun** [comment]
Any chance of getting this published @developit 😄

**Comment by developit** [comment]
Yup yup.

**Comment by UnwrittenFun** [comment]
ty! 🌮
